sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: dingyu
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tLXBVXe4DRnrjJNPy56
    access-key-secret: YzaJxLRz2dpnvY7KlvHKH3gJ04SbgZ
    bucket-name: sky-take-out
  redis:
    host: localhost
    port: 6379
    password: dingyu
    database: 10
  wechat:
    appid: wx72157da9e3968345
    secret: d6377313f3ac3bd12b0732a82cc326a4
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php